### ISSUE TITLE
String.next_grapheme vs Regular Expression

### ISSUE THREAD

**Issue by billc** [JEG2/advent_of_code_2016#1]
I love the simplicity of your code over mine. You have great organizational structure and the code is easy to follow. 

A question for you:  `String.next_grapheme/1` was a function I was unfamiliar with and perfect for the job. Yet, in the second problem you switched to a regular expression. What was the reason?

**Comment by JEG2** [comment]
I did like `String.next_grapheme/1`, but it gave me a structure like `[{"L", "2"}, {"R", "13"}, …]` and I wanted to get to a flat stream of events:  `["L", "2", "R", "13", …]`.  It may not have been a wise trade though.

**Comment by billc** [comment]
Gotcha! I used a pattern match on the function to break up the string
binary into direction and distance i.e '"L" <> distance'. The grapheme
method appears simpler.

Hopefully I can stop wrestling with Spacemacs on Windows not tabbing in the
Elixir layer and catch up on Day 2. Look forward to comparing your
solutions.

-- 
Bill Christian
